### ISSUE TITLE
Hide sensitive information

### ISSUE THREAD

**Issue by AndrewSadikov** [Pillbug23/cs361_fitness_tracker#1]
backend/database/db-connector.js

**This file features database credentials** 
There are a couple of options when it comes to hiding these; here is one:

The most common approach is to use a .env file to store environment variables.
The file itself would be added to your gitignore to avoid secrets showing up in the repo.
This is a popular choice because all major pipelines support environment variables.
This means you can still deploy seamlessly once you configure your ci/cd.

**Comment by Pillbug23** [comment]
Created .env file in backend directory to hide school database credientials
